### ISSUE TITLE
data_format arg_scope

### ISSUE THREAD

**Issue by ilkarman** [pudae/tensorflow-densenet#12]
Pudae, apologies you mentioned this in another issue but I couldn't get it work.

If I create symbol like so:

`densenet.densenet_arg_scope(data_format='NCHW')`

I get

> TypeError: densenet_arg_scope() got an unexpected keyword argument 'data_format'

If I do this:

```
        dense_args = densenet.densenet_arg_scope()
        dense_args['data_format'] = "NCHW"  # This doesn't work!
        print(dense_args)
        with slim.arg_scope(dense_args):
            base_model, _ = densenet.densenet121(in_tensor,
                                                 num_classes=out_features,
                                                 is_training=is_training)
```

Tensorflow just seems to ignore it and use NHWC

**Comment by pudae** [comment]
I Added feature for supporting NCHW.  [[Support NCHW](https://github.com/pudae/tensorflow-densenet/commit/ab416)]
Please check if it helps you. 
Thank you.

**Comment by ilkarman** [comment]
This is perfect thank you! Out of interest I compared to training time of Keras(TF) model and [this TF-one](https://github.com/ilkarman/DeepLearningFrameworks/blob/ikdev2/notebooks/Tensorflow_MultiGPU.ipynb) was 17min10s and [Keras](https://github.com/ilkarman/DeepLearningFrameworks/blob/ikdev2/notebooks/Keras_TF_MultiGPU.ipynb) was 18min30s for 5 epochs on 4xP100s (with synthetic data).

I just also wanted to test if passing `fused=True` to batchnorm would speed up performance
