### ISSUE TITLE
How to get more predict info?

### ISSUE THREAD

**Issue by huiofficial** [pudae/tensorflow-densenet#18]
I am starting to learn tf and I am very much appreciate your work. I use your prediction code and run it successfully, however, the output is only the top-1 guess. How can I get top-5 guesses and the top-5 probabilities? I try to use `tf.nn.top_k` and `tf.nn.in_top_k` but I ran into problems that I cannot solve.

**Comment by tzattack** [comment]
I figure it out. lol.
```
topn = tf.nn.top_k(tf.nn.softmax(logits), 5)
topnind = topn.indices
topnval = topn.values
top_5_guess, top_5_prob = sess.run((topnind,topnval), feed_dict={image_X: input_image})
```
