### ISSUE TITLE
What is DenseNet 161?

### ISSUE THREAD

**Issue by yxiong** [pudae/tensorflow-densenet#2]
Thanks for making this available!

I couldn't figure out the naming scheme of DenseNet in the paper, and would like to ask a quick question here. In table 1 of the paper, there are "DenseNet-121", "DenseNet-169", "DenseNet-201" and "DenseNet-264", but didn't mention "DenseNet-161", which you provided in the pre-trained model. The paper did mention "our largest model (DenseNet-161) ...", but I couldn't find more details about it. Could you provide some pointer or more details about that please? Thanks!

**Comment by pudae** [comment]
The detail about DenseNet-161 architecture can be found from [the official DenseNet implementation](https://github.com/liuzhuang13/DenseNet). Thanks~

**Comment by yxiong** [comment]
Got it. Thanks!
